# Discovery Server Eureka
eureka:
  client:
    serviceUrl:
      default-zone: http://localhost:8761/eureka
  instance:
    status-page-url: /infoPacientes
    health-check-url-path: /healthPacientes
    metadata-map:
      app-owner: cramirez
      description: API generada para el curso de arquitectura de microservicios

# HTTP Server
server:
  port: 3333

# Spring Boot
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: apipaciente
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/api-curso-arquitectura-microservicios
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    continue-on-error: true